### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by isaka-james** [vincent-laizer/UDOM-Ratiba-API#1]
I want to make a flask application using your api, but i found difficult to  use your api because of the poor documentation, please reconsider the documentation or is it I'm the only one getting harder to understand this. I liked the documentation that you made with the nectaapi. @vincent-laizer

**Comment by vincent-laizer** [comment]
I'll look into modifying the documentation and the entire structure of the app. Honestly, it was made out of haste that's why it is poorly written.

**Comment by isaka-james** [comment]
haha @vincent-laizer , you even made me to make my own [UDOM API](https://github.com/reprogamaco/UDOM-RATIBA-API) . I got inspiration ⭐
